{% set name = "phasefieldx" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CastillonMiguel/phasefieldx/archive/v{{ version }}.tar.gz
  sha256: f434c699c92575ed79576f7b266631e4e8bfc4c2b2b0d940b9efb715361339c6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: True  # [win]

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - fenics-dolfinx ==0.9.0
    - gmsh
    - matplotlib-base
    - mpi4py
    - mpich
    - pandas
    - petsc4py
    - numpy
    - pyvista
    - time

test:
  imports:
    - phasefieldx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/CastillonMiguel/phasefieldx
  summary: 'PhaseFieldX: An Open-Source Framework for Advanced Phase-Field Simulations'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://phasefieldx.readthedocs.io
  dev_url: https://github.com/CastillonMiguel/phasefieldx

extra:
  feedstock-name: phasefieldx
  recipe-maintainers:
    - CastillonMiguel
