{% set name = "phasefieldx" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CastillonMiguel/phasefieldx/archive/v{{ version }}.tar.gz
  sha256: f434c699c92575ed79576f7b266631e4e8bfc4c2b2b0d940b9efb715361339c6

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
    - if: mpi == 'openmpi' and build_platform != target_platform
      then: ${{ mpi }}
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - python
        - nanobind
  host:
    - fenics-libbasix ${{ fenics_version }}
    - fenics-basix ${{ fenics_version }}
    - fenics-libdolfinx ${{ fenics_version }}
    - fenics-dolfinx ${{ fenics_version }}
    - ${{ mpi }}
    - petsc
    - petsc * ${{ scalar }}_*
    - pip
    - python
    - scikit-build-core
    - nanobind
  run:
    - python
    - fenics-basix
    - fenics-dolfinx
    - packaging
    - adios2 * mpi_${{ mpi }}_*
    - gmsh
    - pandas
    - pyvista
    - numpy
  run_constraints:
    # require mpi build of h5py
    - h5py * mpi_${{ mpi }}_*

tests:
  - python:
      imports:
        - scifem
      pip_check: true

about:
  home: https://github.com/CastillonMiguel/phasefieldx
  summary: 'PhaseFieldX: An Open-Source Framework for Advanced Phase-Field Simulations'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://phasefieldx.readthedocs.io
  dev_url: https://github.com/CastillonMiguel/phasefieldx

extra:
  recipe-maintainers:
    - CastillonMiguel
